CREATE OR REPLACE TRIGGER hr.HR_HTT_BRI_TRG
-- PL/SQL Block
 BEFORE INSERT
 ON hr.hr_test
 FOR EACH ROW
BEGIN
IF :NEW.ID IS NULL THEN
   SELECT HR_HTT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END IF;
END;
/